name: Publish npm

on:
  push:
    tags:
      - "nessi-v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile --registry=https://registry.npmjs.org
      - name: Typecheck
        run: bun run --filter @valentinkolb/nessi typecheck
      - name: Test
        run: bun run --filter @valentinkolb/nessi test
      - name: Build npm package
        run: bun run build:nessi

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile --registry=https://registry.npmjs.org

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Use npm 11.5.1+
        run: npm install -g npm@11.5.1

      - name: Set version from tag
        run: cd packages/nessi && npm version ${GITHUB_REF#refs/tags/nessi-v} --no-git-tag-version --allow-same-version

      - name: Build npm package
        run: bun run build:nessi

      - name: Publish @valentinkolb/nessi
        run: npm publish --provenance --access public
        working-directory: ./packages/nessi/dist
